BPMSPL-690: Initial standalone image for Standalone Controller
jboss-container-images/jboss-bpmsuite-7-image pull request #6
Opened 2017-07-20 14:11 UTC by rbarriuso

Also updated product envs of business central and kie-server

2017-07-20 14:12 UTC, rbarriuso commented on standalonecontroller/image.yaml
> +    - artifact: jboss-bpmsuite-7.0.0.test20170720-standalone-controller-ee7.zip
This is a temporary artifact until the standalone controller product artifacts are available

2017-07-26 14:29 UTC, goldmann commented on standalonecontroller/image.yaml
> +    - name: "JBOSS_BPMSUITE_VERSION"
Wasn't the conclusion to change this env variable too to follow what's in `JBOSS_PRODUCT`?

2017-07-26 14:31 UTC, goldmann commented on standalonecontroller/image.yaml
> +    - name: "JBOSS_BPMSUITE_VERSION"
In other words - shouldn't it be: `JBOSS_BPMSUITE_STANDALONECONTROLLER_VERSION`?

2017-07-26 14:45 UTC, rbarriuso commented on standalonecontroller/image.yaml
> +    - name: "JBOSS_BPMSUITE_VERSION"
Ops, I'll fix it

2017-07-26 14:57 UTC, errantepiphany commented on standalonecontroller/image.yaml
> +    - name: "JBOSS_BPMSUITE_VERSION"
Thanks @rbarriuso . Please let us know when it's ready so this PR can get processed. :)

2017-07-26 14:59 UTC, errantepiphany commented on standalonecontroller/image.yaml
> +    - artifact: jboss-bpmsuite-7.0.0.test20170720-standalone-controller-ee7.zip
@rbarriuso I see this has been uploaded into http://ce-cacher.usersys.redhat.com/ . Thanks!

2017-07-26 15:01 UTC, rbarriuso commented on standalonecontroller/image.yaml
> +    - artifact: jboss-bpmsuite-7.0.0.test20170720-standalone-controller-ee7.zip
Actually now I'm changing it to use the latest "official" artifact "jboss-brms-bpmsuite-7.0.0.ER-redhat-1-execution-server-controller-ee7.zip". I'll push it soon

2017-07-26 15:09 UTC, rbarriuso commented
@goldmann I've also changed the images versions to match the artifacts used

2017-07-26 15:26 UTC, goldmann commented on standalonecontroller/image.yaml
> +    - artifact: jboss-bpmsuite-7.0.0.test20170720-standalone-controller-ee7.zip
Updated comment, don't leak internal resources.

2017-07-26 15:29 UTC, goldmann requested changes

2017-07-26 15:29 UTC, goldmann commented on businesscentral/image.yaml
> +version: "7.0.0.CAP02"
This should be `7.0.0`.

2017-07-26 15:29 UTC, goldmann commented on businesscentral/image.yaml
> +      value: "7.0.0.CAP02"
This should be `7.0.0`. Besides this you need to update all envs, not just one of them, if you do so.

2017-07-26 15:35 UTC, rbarriuso commented on businesscentral/image.yaml
> +      value: "7.0.0.CAP02"
Changing this env I just intended to express that the version of the inner artifact used was that one. The complete product version could still be a different one. In any case, I'll change all back to 7.0.0

2017-07-26 15:37 UTC, rbarriuso commented
Changed versions

2017-07-26 15:40 UTC, goldmann approved these changes

2017-07-26 15:41 UTC, merged